FROM python:3.11-slim
LABEL maintainer="Trabalho Docker - Link Extractor API (Python + Redis)"

ENV REDIS_URL=redis://redis:6379

WORKDIR /app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY linkextractor.py main.py /app/

EXPOSE 5000
CMD ["python", "main.py"]
