FROM python:3
LABEL maintainer="Joey"

WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY linkextractor.py /app/
COPY main-no-cache.py /app/main.py
RUN chmod a+x /app/*.py

CMD ["./main.py"]
