services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./data/wp_data:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql

  wordpress2:
     image: wordpress:5.4.2-php7.2-apache
     environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_USER: wpuser
       WORDPRESS_DB_PASSWORD: wppass
     volumes:
       - ./data/wp_data:/var/www/html
     networks:
       - backend
     depends_on:
       - mysql

  wordpress3:
     image: wordpress:5.4.2-php7.2-apache
     environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
     volumes:
       - ./data/wp_data:/var/www/html
     networks:
       - backend
     depends_on:
       - mysql

  nginx:
    image: nginx:1.19.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/wp_data:/usr/share/nginx/html
    networks:
      - backend
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

  locust:
    image: locustio/locust
    command: -f /locust/locustfile_cenario3.py --host http://nginx --web-host 0.0.0.0
    volumes:
      - ./locust:/locust
    ports:
      - "8089:8089"
    networks:
      - backend
    depends_on:
      - nginx        

networks:
  backend: