version: "3.8"

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  wordpress1:
    image: wordpress:php7.4-apache
    container_name: wordpress1
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./data/wp:/var/www/html/wp-content/uploads
    networks:
      - backend
    depends_on:
      - mysql

  wordpress2:
    image: wordpress:php7.4-apache
    container_name: wordpress2
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./data/wp:/var/www/html/wp-content/uploads
    networks:
      - backend
    depends_on:
      - mysql

  wordpress3:
    image: wordpress:php7.4-apache
    container_name: wordpress3
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
    volumes:
      - ./data/wp:/var/www/html/wp-content/uploads
    networks:
      - backend
    depends_on:
      - mysql

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    networks:
      - backend

  locust:
    image: locustio/locust
    container_name: locust
    command: -f /locust/locustfile_cenario3.py --host http://nginx --web-host 0.0.0.0
    volumes:
      - ./locust:/locust
    ports:
      - "8089:8089"
    depends_on:
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge