version: '3'

services:
  api:
    image: linkextractor-api:python-no-cache
    build:
      context: ./api
      dockerfile: Dockerfile.python-no-cache
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://localhost:6379
    networks:
      - test-net

  web:
    image: linkextractor-web:php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    depends_on:
      - api
    networks:
      - test-net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - test-net

networks:
  test-net:
